version: '3'
services:
  fifo-webserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TYPE: FIFO
    privileged: true
    ports:
    - "80:8001"
    volumes:
    - ./default:/app/default
    - ./webserver-fifo.conf:/etc/webserver/config.conf
    command: /bin/bash
    tty: true
    stdin_open: true
  fork-webserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TYPE: FORK
    privileged: true
    ports:
    - "81:8002"
    volumes:
    - ./default:/app/default
    - ./webserver-fork.conf:/etc/webserver/config.conf
    command: /bin/bash
    tty: true
    stdin_open: true
volumes:
  logvolumefifo: {}