version: '3'
services:
  fifo-webserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TYPE: FIFO
    privileged: true
    ports:
    - "8001:8001"
    volumes:
    - ./default:/app/default
    - ./webserver-fifo.conf:/etc/webserver/config.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty: true
    stdin_open: true
  fork-webserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TYPE: FORK
    privileged: true
    ports:
    - "8003:8003"
    volumes:
    - ./default:/app/default
    - ./webserver-fork.conf:/etc/webserver/config.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty: true
    stdin_open: true
  threaded-webserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TYPE: THREADED
    privileged: true
    ports:
    - "8005:8005"
    volumes:
    - ./default:/app/default
    - ./webserver-threaded.conf:/etc/webserver/config.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty: true
    stdin_open: true
  prethreaded-webserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TYPE: PRETHREADED
    privileged: true
    ports:
    - "8007:8007"
    volumes:
    - ./default:/app/default
    - ./webserver-prethreaded.conf:/etc/webserver/config.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty: true
    stdin_open: true
  prefork-webserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TYPE: PREFORK
    privileged: true
    ports:
    - "8009:8009"
    volumes:
    - ./default:/app/default
    - ./webserver-prefork.conf:/etc/webserver/config.conf
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty: true
    stdin_open: true